name: Generate snake

on:
  schedule:
    - cron: "0 */12 * * *"  
  workflow_dispatch:         
  push:
    branches: ["main", "master"]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write 
    steps:
      - name: Generate the snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: Jennmml
          outputs: dist/github-contribution-grid-snake.svg

      - name: Publish to output branch
        uses: crazy-max/ghaction-github-pages@v4
        if: success()
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
